package com.knoxhack.echogalacticcore.nativeapi;

import com.knoxhack.echogalacticcore.EchoGalacticCoreNativeModule;
import com.knoxhack.echogalacticcore.GalacticCoreIds;
import dev.echo.nativeplatform.contracts.EchoNativeLoadStatus;
import dev.echo.nativeplatform.contracts.EchoNativeModuleDescriptor;
import dev.echo.nativeplatform.contracts.EchoNativeModuleLoadContext;
import dev.echo.nativeplatform.contracts.EchoNativeMutationReceipt;
import dev.echo.nativeplatform.contracts.EchoNativeRuntimeSide;
import dev.echo.nativeplatform.testkit.EchoNativeSdkTestkit;
import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class EchoGalacticCoreNativeModuleTest {
    @Test
    void nativeModuleRegistersAllRequiredTypedSurfaces() {
        EchoNativeSdkTestkit.Environment env = EchoNativeSdkTestkit.common(GalacticCoreIds.MOD_ID);
        EchoNativeModuleLoadContext context = new EchoNativeModuleLoadContext(descriptor(), env.serviceRegistry(), Map.of());
        EchoGalacticCoreNativeModule module = new EchoGalacticCoreNativeModule();

        module.discover(context);
        module.resolve(context);
        module.loadClasses(context);
        module.construct(context);
        module.registerServices(context);
        module.registerContent(context);
        module.commonSetup(context);
        module.clientSetup(context);
        module.serverSetup(context);
        module.ready(context);
        module.shutdown(context);

        env.goldenParity().requireNoFailedReceipts();
        env.goldenParity().requireOnlyTypedReceipts();
        env.goldenParity().requireMutatedServices(
                "echo.native.registry",
                "echo.native.lifecycle",
                "echo.native.events",
                "echo.native.commands",
                "echo.native.config",
                "echo.native.network",
                "echo.native.resources",
                "echo.native.capabilities",
                "echo.native.attachments",
                "echo.native.worldgen",
                "echo.native.render",
                "echo.native.screens",
                "echo.native.save_data"
        );
        env.goldenParity().requireMutatedSurfaces(
                "registry",
                "lifecycle",
                "events",
                "commands",
                "config",
                "network",
                "resources",
                "capabilities",
                "attachments",
                "worldgen",
                "render",
                "screens",
                "save_data"
        );
        assertTrue(context.mutationReceipts().stream().anyMatch(EchoNativeMutationReceipt::mutated));
        assertFalse(context.mutationReceipts().stream()
                .anyMatch(receipt -> receipt.status() == EchoNativeLoadStatus.FAILED));
        assertTrue(hasReceipt(
                context,
                "echo.native.worldgen",
                "worldgen",
                "placeStructure",
                GalacticCoreIds.id("dungeon/moon_dungeon_tier_1")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.registry",
                "registry",
                "deferredRegister",
                GalacticCoreIds.id("boss/evolved_skeleton_boss")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.resources",
                "resources",
                "registerReloadListener",
                GalacticCoreIds.id("loot/moon_dungeon_tier_1")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.resources",
                "resources",
                "registerReloadListener",
                GalacticCoreIds.id("gameplay/foundation")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.resources",
                "resources",
                "registerReloadListener",
                GalacticCoreIds.id("gameplay/machines")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.resources",
                "resources",
                "registerReloadListener",
                GalacticCoreIds.id("gameplay/life_support")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.resources",
                "resources",
                "registerReloadListener",
                GalacticCoreIds.id("gameplay/rocket_progression")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.resources",
                "resources",
                "registerReloadListener",
                GalacticCoreIds.id("gameplay/energy_bridge")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.resources",
                "resources",
                "registerReloadListener",
                GalacticCoreIds.id("gameplay/player_gear")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.resources",
                "resources",
                "registerReloadListener",
                GalacticCoreIds.id("gameplay/celestial_environments")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.resources",
                "resources",
                "registerReloadListener",
                GalacticCoreIds.id("gameplay/outer_planet_progression")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.resources",
                "resources",
                "registerReloadListener",
                GalacticCoreIds.id("gameplay/dungeon_reward_progression")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.resources",
                "resources",
                "registerReloadListener",
                GalacticCoreIds.id("gameplay/dungeon_boss_parity")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.resources",
                "resources",
                "registerReloadListener",
                GalacticCoreIds.id("gameplay/celestial_routes")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.resources",
                "resources",
                "registerReloadListener",
                GalacticCoreIds.id("gameplay/echo_integrations")
        ));
        assertTrue(hasReceipt(
                context,
                "echo.native.screens",
                "screens",
                "registerSurface",
                GalacticCoreIds.id("treasure_chest")
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "installRuntimeModel",
                GalacticCoreIds.id("runtime/gameplay_models"),
                "galacticraft_legacy_runtime_parity"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.save_data",
                "save_data",
                "write",
                GalacticCoreIds.id("runtime/default_machine_states"),
                "galacticraft_legacy_runtime_parity"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.attachments",
                "attachments",
                "attach",
                GalacticCoreIds.id("runtime/player_progression_state"),
                "galacticraft_legacy_runtime_parity"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.save_data",
                "save_data",
                "write",
                GalacticCoreIds.id("runtime/route_and_dungeon_progression"),
                "galacticraft_legacy_runtime_parity"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.worldgen",
                "worldgen",
                "registerFeature",
                GalacticCoreIds.id("runtime/environment_scan_models"),
                "galacticraft_legacy_runtime_parity"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "installRuntimeGateway",
                GalacticCoreIds.id("runtime/gateway"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/machine_tick"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/player_tick_life_support"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.network",
                "network",
                "sendToPlayer",
                GalacticCoreIds.id("packet/holomap_route_interaction"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.network",
                "network",
                "sendToPlayer",
                GalacticCoreIds.id("packet/screencore_launch_checklist_interaction"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.network",
                "network",
                "sendToPlayer",
                GalacticCoreIds.id("packet/celestial_route_action"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.network",
                "network",
                "broadcast",
                GalacticCoreIds.id("packet/dungeon_reward_claim"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/boss_entity_spawn"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/boss_encounter_tick"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/boss_ai_step"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.network",
                "network",
                "broadcast",
                GalacticCoreIds.id("packet/dungeon_treasure_interaction"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen/launch_checklist"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen/holomap_routes"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen/screencore_launch_checklist"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen_layout/holomap_routes"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen_layout/screencore_launch_checklist"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen_layout/treasure_chest"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen/treasure_chest"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.worldgen",
                "worldgen",
                "registerFeature",
                GalacticCoreIds.id("worldgen/dungeon_structure/moon"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.worldgen",
                "worldgen",
                "placeStructure",
                GalacticCoreIds.id("worldgen/transfer_placement/moon"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/dimension_transfer_execute"),
                "galacticraft_legacy_runtime_gateway"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "installRuntimeAdapters",
                GalacticCoreIds.id("runtime/adapters"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.save_data",
                "save_data",
                "write",
                GalacticCoreIds.id("runtime/adapter_state_contracts"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.worldgen",
                "worldgen",
                "registerFeature",
                GalacticCoreIds.id("runtime/dungeon_encounter_adapters"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.worldgen",
                "worldgen",
                "registerFeature",
                GalacticCoreIds.id("worldgen/dungeon_structure_adapter/moon"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.worldgen",
                "worldgen",
                "placeStructure",
                GalacticCoreIds.id("worldgen/transfer_placement/moon"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/dimension_transfer_execute"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen/holomap_routes"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen/screencore_launch_checklist"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen_layout/holomap_routes"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen_layout/screencore_launch_checklist"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen_layout/treasure_chest"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen/treasure_chest"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.network",
                "network",
                "sendToPlayer",
                GalacticCoreIds.id("packet/holomap_route_interaction"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.network",
                "network",
                "sendToPlayer",
                GalacticCoreIds.id("packet/screencore_launch_checklist_interaction"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/boss_entity_spawn"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/boss_encounter_tick"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/boss_ai_step"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.network",
                "network",
                "broadcast",
                GalacticCoreIds.id("packet/dungeon_treasure_interaction"),
                "galacticraft_legacy_runtime_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "installHostCallbacks",
                GalacticCoreIds.id("runtime/host_callbacks"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.lifecycle",
                "lifecycle",
                "registerGameTest",
                GalacticCoreIds.id("gametest/host_callback_smoke"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_dungeon_structure_prepare"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_boss_entity_spawn"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_boss_encounter_tick"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_boss_ai_step"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_dungeon_treasure_interaction"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_treasure_chest_screen_open"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_transfer_placement_prepare"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_dimension_transfer_execute"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_holomap_route_surface_open"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_holomap_route_interaction"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_screencore_launch_checklist_open"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_screencore_launch_checklist_interaction"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_holomap_route_menu_render"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_screencore_launch_checklist_menu_render"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_treasure_chest_menu_render"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "subscribe",
                GalacticCoreIds.id("event/host_machine_block_entity_tick"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/machine_tick"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.network",
                "network",
                "sendToPlayer",
                GalacticCoreIds.id("packet/celestial_route_action"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.network",
                "network",
                "broadcast",
                GalacticCoreIds.id("packet/dungeon_reward_claim"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen/celestial_selection"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen/holomap_routes"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen/screencore_launch_checklist"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen_layout/holomap_routes"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen_layout/screencore_launch_checklist"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen_layout/treasure_chest"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen/treasure_chest"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.network",
                "network",
                "sendToPlayer",
                GalacticCoreIds.id("packet/holomap_route_interaction"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.network",
                "network",
                "sendToPlayer",
                GalacticCoreIds.id("packet/screencore_launch_checklist_interaction"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/boss_entity_spawn"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/boss_encounter_tick"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/boss_ai_step"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.network",
                "network",
                "broadcast",
                GalacticCoreIds.id("packet/dungeon_treasure_interaction"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.worldgen",
                "worldgen",
                "registerFeature",
                GalacticCoreIds.id("worldgen/dungeon_structure_host/moon"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.worldgen",
                "worldgen",
                "placeStructure",
                GalacticCoreIds.id("worldgen/transfer_placement/moon"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/dimension_transfer_execute"),
                "galacticraft_legacy_host_callbacks"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "installHostExecutionBridge",
                GalacticCoreIds.id("runtime/host_execution_bridge"),
                "galacticraft_legacy_host_execution_bridge"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.lifecycle",
                "lifecycle",
                "registerGameTest",
                GalacticCoreIds.id("gametest/host_execution_bridge_smoke"),
                "galacticraft_legacy_host_execution_bridge"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.save_data",
                "save_data",
                "write",
                GalacticCoreIds.id("runtime/host_execution_state_contracts"),
                "galacticraft_legacy_host_execution_bridge"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/host_execution_dimension_transfer"),
                "galacticraft_legacy_host_execution_bridge"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.events",
                "events",
                "publish",
                GalacticCoreIds.id("event/host_execution_boss_spawn"),
                "galacticraft_legacy_host_execution_bridge"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen_layout/host_binding/holomap_routes"),
                "galacticraft_legacy_host_execution_bridge"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen_layout/host_binding/screencore_launch_checklist"),
                "galacticraft_legacy_host_execution_bridge"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("screen_layout/host_binding/treasure_chest"),
                "galacticraft_legacy_host_execution_bridge"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "installConcreteHostBindings",
                GalacticCoreIds.id("runtime/concrete_host_bindings"),
                "galacticraft_legacy_concrete_host_bindings"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.lifecycle",
                "lifecycle",
                "registerGameTest",
                GalacticCoreIds.id("gametest/concrete_host_binding_smoke"),
                "galacticraft_legacy_concrete_host_bindings"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.save_data",
                "save_data",
                "write",
                GalacticCoreIds.id("runtime/concrete_host_binding_state_contracts"),
                "galacticraft_legacy_concrete_host_bindings"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.worldgen",
                "worldgen",
                "placeStructure",
                GalacticCoreIds.id("host_binding/world_dimension_transfer"),
                "galacticraft_legacy_concrete_host_bindings"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "registerIntegration",
                GalacticCoreIds.id("host_binding/entity_boss_spawn"),
                "galacticraft_legacy_concrete_host_bindings"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "registerMenu",
                GalacticCoreIds.id("host_binding/screen_holomap_routes"),
                "galacticraft_legacy_concrete_host_bindings"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "registerMenu",
                GalacticCoreIds.id("host_binding/screen_screencore_launch_checklist"),
                "galacticraft_legacy_concrete_host_bindings"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "registerMenu",
                GalacticCoreIds.id("host_binding/screen_treasure_chest"),
                "galacticraft_legacy_concrete_host_bindings"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "installLiveHostAdapters",
                GalacticCoreIds.id("runtime/live_host_adapters"),
                "galacticraft_legacy_live_host_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.lifecycle",
                "lifecycle",
                "registerGameTest",
                GalacticCoreIds.id("gametest/live_host_adapter_smoke"),
                "galacticraft_legacy_live_host_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.save_data",
                "save_data",
                "write",
                GalacticCoreIds.id("runtime/live_host_adapter_state_contracts"),
                "galacticraft_legacy_live_host_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.worldgen",
                "worldgen",
                "placeStructure",
                GalacticCoreIds.id("live_host/world_dimension_transfer"),
                "galacticraft_legacy_live_host_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "registerIntegration",
                GalacticCoreIds.id("live_host/entity_boss_spawn"),
                "galacticraft_legacy_live_host_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("live_host/screen_holomap_routes"),
                "galacticraft_legacy_live_host_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("live_host/screen_screencore_launch_checklist"),
                "galacticraft_legacy_live_host_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("live_host/screen_treasure_chest"),
                "galacticraft_legacy_live_host_adapters"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "installLiveHostEntrypoints",
                GalacticCoreIds.id("runtime/live_host_entrypoints"),
                "galacticraft_legacy_live_host_entrypoints"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.lifecycle",
                "lifecycle",
                "registerGameTest",
                GalacticCoreIds.id("gametest/live_host_entrypoint_smoke"),
                "galacticraft_legacy_live_host_entrypoints"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.save_data",
                "save_data",
                "write",
                GalacticCoreIds.id("runtime/live_host_entrypoint_state_contracts"),
                "galacticraft_legacy_live_host_entrypoints"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.worldgen",
                "worldgen",
                "placeStructure",
                GalacticCoreIds.id("live_callback/world_dimension_transfer"),
                "galacticraft_legacy_live_host_entrypoints"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "registerIntegration",
                GalacticCoreIds.id("live_callback/entity_boss_spawn"),
                "galacticraft_legacy_live_host_entrypoints"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("live_callback/screen_holomap_routes"),
                "galacticraft_legacy_live_host_entrypoints"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("live_callback/screen_screencore_launch_checklist"),
                "galacticraft_legacy_live_host_entrypoints"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("live_callback/screen_treasure_chest"),
                "galacticraft_legacy_live_host_entrypoints"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "installPlatformExecutors",
                GalacticCoreIds.id("runtime/platform_executors"),
                "galacticraft_legacy_platform_executor_facade"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.lifecycle",
                "lifecycle",
                "registerGameTest",
                GalacticCoreIds.id("gametest/platform_executor_smoke"),
                "galacticraft_legacy_platform_executor_facade"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.save_data",
                "save_data",
                "write",
                GalacticCoreIds.id("runtime/platform_executor_state_contracts"),
                "galacticraft_legacy_platform_executor_facade"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.worldgen",
                "worldgen",
                "placeStructure",
                GalacticCoreIds.id("platform_executor/world_dimension_transfer"),
                "galacticraft_legacy_platform_executor_facade"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "registerIntegration",
                GalacticCoreIds.id("platform_executor/entity_boss_spawn"),
                "galacticraft_legacy_platform_executor_facade"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("platform_executor/screen_holomap_routes"),
                "galacticraft_legacy_platform_executor_facade"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("platform_executor/screen_screencore_launch_checklist"),
                "galacticraft_legacy_platform_executor_facade"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("platform_executor/screen_treasure_chest"),
                "galacticraft_legacy_platform_executor_facade"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "installLiveSessionMutations",
                GalacticCoreIds.id("runtime/live_session_mutations"),
                "galacticraft_legacy_live_session_mutation_bridge"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.lifecycle",
                "lifecycle",
                "registerGameTest",
                GalacticCoreIds.id("gametest/live_session_mutation_smoke"),
                "galacticraft_legacy_live_session_mutation_bridge"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.save_data",
                "save_data",
                "write",
                GalacticCoreIds.id("runtime/live_session_mutation_state_contracts"),
                "galacticraft_legacy_live_session_mutation_bridge"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.worldgen",
                "worldgen",
                "placeStructure",
                GalacticCoreIds.id("live_session/world_dimension_transfer"),
                "galacticraft_legacy_live_session_mutation_bridge"
        ));
        assertTrue(hasReceiptEvidence(
                context,
                "echo.native.worldgen",
                GalacticCoreIds.id("live_session/world_dimension_transfer"),
                "payloadHostApi",
                "loadDestinationAndPlacePlayer"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.capabilities",
                "capabilities",
                "registerIntegration",
                GalacticCoreIds.id("live_session/entity_boss_spawn"),
                "galacticraft_legacy_live_session_mutation_bridge"
        ));
        assertTrue(hasReceiptEvidence(
                context,
                "echo.native.capabilities",
                GalacticCoreIds.id("live_session/entity_boss_spawn"),
                "payloadHostApi",
                "spawnBossEntityAndAttachEncounter"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("live_session/screen_holomap_routes"),
                "galacticraft_legacy_live_session_mutation_bridge"
        ));
        assertTrue(hasReceiptEvidence(
                context,
                "echo.native.screens",
                GalacticCoreIds.id("live_session/screen_holomap_routes"),
                "payloadHostApi",
                "openScreenAndMountState"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("live_session/screen_screencore_launch_checklist"),
                "galacticraft_legacy_live_session_mutation_bridge"
        ));
        assertTrue(hasReceiptWithSource(
                context,
                "echo.native.screens",
                "screens",
                "open",
                GalacticCoreIds.id("live_session/screen_treasure_chest"),
                "galacticraft_legacy_live_session_mutation_bridge"
        ));
        assertTrue(context.serviceRegistry().hasService(
                GalacticCoreIds.MOD_ID,
                GalacticCoreIds.id("port_plan")
        ));
        assertTrue(context.serviceRegistry().hasService(
                GalacticCoreIds.MOD_ID,
                GalacticCoreIds.id("runtime")
        ));
        assertTrue(context.serviceRegistry().hasService(
                GalacticCoreIds.MOD_ID,
                GalacticCoreIds.id("runtime_gateway")
        ));
        assertTrue(context.serviceRegistry().hasService(
                GalacticCoreIds.MOD_ID,
                GalacticCoreIds.id("runtime_adapters")
        ));
        assertTrue(context.serviceRegistry().hasService(
                GalacticCoreIds.MOD_ID,
                GalacticCoreIds.id("host_callbacks")
        ));
        assertTrue(context.serviceRegistry().hasService(
                GalacticCoreIds.MOD_ID,
                GalacticCoreIds.id("host_execution_bridge")
        ));
        assertTrue(context.serviceRegistry().hasService(
                GalacticCoreIds.MOD_ID,
                GalacticCoreIds.id("host_binding_contracts")
        ));
        assertTrue(context.serviceRegistry().hasService(
                GalacticCoreIds.MOD_ID,
                GalacticCoreIds.id("live_host_adapters")
        ));
        assertTrue(context.serviceRegistry().hasService(
                GalacticCoreIds.MOD_ID,
                GalacticCoreIds.id("live_host_entrypoints")
        ));
        assertTrue(context.serviceRegistry().hasService(
                GalacticCoreIds.MOD_ID,
                GalacticCoreIds.id("platform_executors")
        ));
        assertTrue(context.serviceRegistry().hasService(
                GalacticCoreIds.MOD_ID,
                GalacticCoreIds.id("live_session_mutations")
        ));
    }

    @Test
    void testkitRejectsDuplicatePacketIds() {
        EchoNativeSdkTestkit.Environment env = EchoNativeSdkTestkit.common(GalacticCoreIds.MOD_ID);

        EchoNativeMutationReceipt first = env.network().registerPacket(env.mutation(
                "network",
                "registerPacket",
                GalacticCoreIds.id("packet/duplicate_check")
        ));
        EchoNativeMutationReceipt second = env.network().registerPacket(env.mutation(
                "network",
                "registerPacket",
                GalacticCoreIds.id("packet/duplicate_check")
        ));

        assertEquals(EchoNativeLoadStatus.MUTATED, first.status());
        assertEquals(EchoNativeLoadStatus.FAILED, second.status());
    }

    @Test
    void moduleFixtureDescriptorUsesNativeEntrypoint() {
        EchoNativeSdkTestkit.Environment env = EchoNativeSdkTestkit.common(GalacticCoreIds.MOD_ID);

        EchoNativeSdkTestkit.ModuleFixture fixture = env.moduleFixture(
                GalacticCoreIds.NATIVE_ENTRYPOINT,
                List.of("echoadaptercore"),
                GalacticCoreIds.OPTIONAL_INTEGRATIONS,
                List.of("galacticcore.content", "galacticcore.rockets", "galacticcore.life_support")
        );

        assertEquals(GalacticCoreIds.MOD_ID, fixture.moduleDescriptor().id());
        assertEquals(GalacticCoreIds.NATIVE_ENTRYPOINT, fixture.moduleDescriptor().entrypoint());
        assertTrue(fixture.moduleDescriptor().requires().contains("echoadaptercore"));
    }

    private static EchoNativeModuleDescriptor descriptor() {
        return new EchoNativeModuleDescriptor(
                GalacticCoreIds.MOD_ID,
                GalacticCoreIds.MOD_NAME,
                GalacticCoreIds.VERSION,
                "addon",
                "space_exploration",
                GalacticCoreIds.NATIVE_ENTRYPOINT,
                EchoNativeRuntimeSide.COMMON,
                List.of("echoadaptercore"),
                GalacticCoreIds.OPTIONAL_INTEGRATIONS,
                List.of("galacticcore.content", "galacticcore.rockets", "galacticcore.life_support"),
                Path.of("src/main/resources/META-INF/echo.mod.json"),
                List.of()
        );
    }

    private static boolean hasReceipt(
            EchoNativeModuleLoadContext context,
            String serviceId,
            String surface,
            String action,
            String target
    ) {
        return hasReceiptWithSource(context, serviceId, surface, action, target, "galacticraft_legacy_mit_port");
    }

    private static boolean hasReceiptWithSource(
            EchoNativeModuleLoadContext context,
            String serviceId,
            String surface,
            String action,
            String target,
            String source
    ) {
        return context.mutationReceipts().stream().anyMatch(receipt ->
                receipt.mutated()
                        && serviceId.equals(receipt.serviceId())
                        && surface.equals(receipt.surface())
                        && action.equals(receipt.action())
                        && target.equals(receipt.target())
                        && source.equals(receipt.evidence().get("source"))
        );
    }

    private static boolean hasReceiptEvidence(
            EchoNativeModuleLoadContext context,
            String serviceId,
            String target,
            String evidenceKey,
            Object evidenceValue
    ) {
        return context.mutationReceipts().stream().anyMatch(receipt ->
                receipt.mutated()
                        && serviceId.equals(receipt.serviceId())
                        && target.equals(receipt.target())
                        && evidenceValue.equals(receipt.evidence().get(evidenceKey))
        );
    }
}
