mod_id=echostationfall
mod_name=ECHO: Stationfall
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.knoxhack.echostationfall
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.29-beta
neo_version_range=[26.1.2.29-beta,)
loader_version_range=[9,)
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
