org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod_id=echomodpackcommandcenter
mod_name=ECHO: Modpack Command Center
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.knoxhack.echo.commandcenter
