org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.29-beta
jei_version=29.5.0.26

mod_id=echoashfallprotocol
mod_name=ECHO: Ashfall Protocol
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.knoxhack.echoashfallprotocol
