package com.knoxhack.echoarcanacore.api;

public enum ArcaneProgressionHook {
    FIRST_ARCANE_SCAN,
    FIRST_AETHER_GAIN,
    FIRST_RELIC_FOUND,
    FIRST_RELIC_SCANNED,
    FIRST_RELIC_DECODED,
    FIRST_RELIC_STABILIZED,
    FIRST_SPELL_UNLOCKED,
    FIRST_SPELL_CAST,
    FIRST_RITUAL_COMPLETED,
    FIRST_RITUAL_FAILED,
    FIRST_CURSE_GAINED,
    FIRST_CURSE_CLEANSED,
    FIRST_FAMILIAR_BONDED,
    FIRST_RIFT_FOUND,
    FIRST_RIFT_ENTERED,
    FIRST_ARCANE_MACHINE_CRAFTED,
    FIRST_GRIMOIRE_ENTRY_READ,
    FIRST_FORBIDDEN_PAGE_READ,
    FIRST_VEILBOUND_RESEARCH_UNLOCKED,
    FIRST_FRACTURE_RIFT_SEALED
}
