package com.knoxhack.echoterminal.client.screen;

import com.echoplatform.echocore.api.config.EchoConfigCategory;
import com.echoplatform.echocore.api.config.EchoConfigEntry;
import com.echoplatform.echocore.api.config.EchoConfigModule;
import com.echoplatform.echocore.api.config.EchoConfigProvider;
import com.echoplatform.echocore.api.config.EchoConfigRegistry;
import com.echoplatform.echocore.api.config.EchoConfigSide;
import com.knoxhack.echoterminal.EchoTerminal;
import java.util.List;

public final class TerminalClientConfigIntegration {
    private TerminalClientConfigIntegration() {
    }

    public static void register() {
        EchoConfigRegistry.register(EchoConfigProvider.of(EchoTerminal.MODID, () -> new EchoConfigModule(
                EchoTerminal.MODID,
                "ECHO Terminal",
                List.of(
                        new EchoConfigCategory("navigation", "Navigation", List.of(
                                EchoConfigEntry.enumEntry("navigation_style", "Navigation Style",
                                        "Terminal navigation layout.",
                                        EchoConfigSide.CLIENT,
                                        TerminalClientOptions.NavigationStyle.APP_HUB,
                                        TerminalClientOptions.NavigationStyle.class,
                                        () -> TerminalClientOptions.navigationStyle,
                                        TerminalClientOptions::selectNavigationStyle,
                                        null, true, false, false))),
                        new EchoConfigCategory("presentation", "Presentation", List.of(
                                EchoConfigEntry.enumEntry("interface_density", "Interface Density",
                                        "Terminal information density.",
                                        EchoConfigSide.CLIENT,
                                        TerminalClientOptions.InterfaceDensity.COMFORTABLE,
                                        TerminalClientOptions.InterfaceDensity.class,
                                        () -> TerminalClientOptions.interfaceDensity,
                                        TerminalClientOptions::selectInterfaceDensity,
                                        null, true, false, false),
                                EchoConfigEntry.enumEntry("terminal_zoom", "Terminal Zoom",
                                        "Terminal interface zoom.",
                                        EchoConfigSide.CLIENT,
                                        TerminalClientOptions.TerminalZoom.ZOOM_90,
                                        TerminalClientOptions.TerminalZoom.class,
                                        () -> TerminalClientOptions.terminalZoom,
                                        TerminalClientOptions::selectTerminalZoom,
                                        null, true, false, false),
                                EchoConfigEntry.enumEntry("visual_level", "Visual Level",
                                        "Terminal visual treatment level.",
                                        EchoConfigSide.CLIENT,
                                        TerminalClientOptions.VisualLevel.BALANCED,
                                        TerminalClientOptions.VisualLevel.class,
                                        () -> TerminalClientOptions.visualLevel,
                                        TerminalClientOptions::selectVisualLevel,
                                        null, true, false, false),
                                EchoConfigEntry.booleanEntry("reduced_motion", "Reduced Motion",
                                        "Reduce terminal motion and heavier animated treatments.",
                                        EchoConfigSide.CLIENT,
                                        false,
                                        TerminalClientOptions::reduceMotion,
                                        TerminalClientOptions::setReducedMotion,
                                        null, true, false, false),
                                EchoConfigEntry.booleanEntry("high_contrast_mode", "High Contrast Mode",
                                        "Use brighter text, stronger status colors, and clearer controls.",
                                        EchoConfigSide.CLIENT,
                                        false,
                                        TerminalClientOptions::highContrastMode,
                                        TerminalClientOptions::setHighContrastMode,
                                        null, true, false, false),
                                EchoConfigEntry.booleanEntry("reduced_clutter_mode", "Reduced Clutter Mode",
                                        "Remove decorative frames, grid noise, image plates, and extra glow.",
                                        EchoConfigSide.CLIENT,
                                        false,
                                        TerminalClientOptions::reducedClutterMode,
                                        TerminalClientOptions::setReducedClutterMode,
                                        null, true, false, false),
                                EchoConfigEntry.booleanEntry("large_text_mode", "Large Text Mode",
                                        "Increase terminal scale, row height, button height, and spacing.",
                                        EchoConfigSide.CLIENT,
                                        false,
                                        TerminalClientOptions::largeTextMode,
                                        TerminalClientOptions::setLargeTextMode,
                                        null, true, false, false),
                                EchoConfigEntry.booleanEntry("simplified_terminal_mode", "Simplified Terminal Mode",
                                        "Prefer a quiet, reduced terminal layout with debug information hidden.",
                                        EchoConfigSide.CLIENT,
                                        false,
                                        TerminalClientOptions::simplifiedTerminalMode,
                                        TerminalClientOptions::setSimplifiedTerminalMode,
                                        null, true, false, false),
                                EchoConfigEntry.booleanEntry("hide_debug_info", "Hide Debug Info",
                                        "Hide raw IDs and debug snapshots unless advanced information is needed.",
                                        EchoConfigSide.CLIENT,
                                        true,
                                        TerminalClientOptions::hideDebugInfo,
                                        TerminalClientOptions::setHideDebugInfo,
                                        null, true, false, false),
                                EchoConfigEntry.booleanEntry("reduce_glow", "Reduce Glow",
                                        "Tone down luminous borders and accent blooms.",
                                        EchoConfigSide.CLIENT,
                                        true,
                                        TerminalClientOptions::reduceGlow,
                                        TerminalClientOptions::setReduceGlow,
                                        null, true, false, false),
                                EchoConfigEntry.booleanEntry("reduce_grid_noise", "Reduce Grid Noise",
                                        "Suppress terminal background grid and scanline texture.",
                                        EchoConfigSide.CLIENT,
                                        true,
                                        TerminalClientOptions::reduceGridNoise,
                                        TerminalClientOptions::setReduceGridNoise,
                                        null, true, false, false),
                                EchoConfigEntry.booleanEntry("mission_hud_notifications", "Mission HUD Notifications",
                                        "Show mission HUD notifications.",
                                        EchoConfigSide.CLIENT,
                                        true,
                                        () -> TerminalClientOptions.missionHudNotifications,
                                        TerminalClientOptions::setMissionHudNotifications,
                                        null, true, false, false))),
                        new EchoConfigCategory("screencore", "ScreenCore", List.of(
                                EchoConfigEntry.booleanEntry("use_screencore", "Use ScreenCore",
                                        "Allow the ScreenCore Terminal shell when ScreenCore is installed.",
                                        EchoConfigSide.CLIENT,
                                        true,
                                        TerminalClientOptions::useScreenCore,
                                        TerminalClientOptions::setUseScreenCore,
                                        null, true, false, false),
                                EchoConfigEntry.booleanEntry("screencore_match_existing_layout",
                                        "Match Existing Layout",
                                        "Keep ScreenCore pages constrained to the current Terminal layout identity.",
                                        EchoConfigSide.CLIENT,
                                        true,
                                        TerminalClientOptions::screenCoreMatchExistingLayout,
                                        TerminalClientOptions::setScreenCoreMatchExistingLayout,
                                        null, true, false, false),
                                EchoConfigEntry.booleanEntry("screencore_debug", "ScreenCore Debug",
                                        "Show ScreenCore diagnostics for Terminal pages.",
                                        EchoConfigSide.CLIENT,
                                        false,
                                        TerminalClientOptions::screenCoreDebug,
                                        TerminalClientOptions::setScreenCoreDebug,
                                        null, true, false, false),
                                EchoConfigEntry.booleanEntry("screencore_experimental_tabs",
                                        "ScreenCore Shell",
                                        "Use the ScreenCore Terminal shell for built-in pages; disable to use the legacy renderer.",
                                        EchoConfigSide.CLIENT,
                                        true,
                                        TerminalClientOptions::screenCoreExperimentalTabs,
                                        TerminalClientOptions::setScreenCoreExperimentalTabs,
                                        null, true, false, false)))))));
    }
}
