
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
mod_id=echomaterialcore
mod_name=ECHO Material Core
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=com.knoxhack.echomaterialcore
mod_authors=KnoxHack
mod_description=Baseline raw materials, refined materials, generic building blocks, and material tags.
