package com.knoxhack.echo.scriptcore.validation;

import java.util.Set;

public final class EchoScriptKnownTypes {
    public static final Set<String> DEFINITION_TYPES = Set.of(
            "mission",
            "archive_entry",
            "lens_scan",
            "holomap_layer",
            "holomap_marker",
            "weather_event",
            "faction",
            "world_state",
            "tutorial_hint",
            "dialogue",
            "ending",
            "recipe_unlock",
            "loot_profile",
            "generic");
    public static final Set<String> CONDITION_TYPES = Set.of(
            "always",
            "never",
            "all",
            "any",
            "not",
            "mission_complete",
            "mission_active",
            "mission_started",
            "objective_complete",
            "item_obtained",
            "item_crafted",
            "item_count_at_least",
            "block_scanned",
            "entity_scanned",
            "item_scanned",
            "poi_discovered",
            "region_entered",
            "weather_survived",
            "faction_reputation_at_least",
            "faction_reputation_below",
            "world_state_set",
            "branch_marker_set",
            "dialogue_choice_made",
            "dimension_entered",
            "biome_entered",
            "time_survived",
            "player_level_at_least",
            "custom_metric_at_least",
            "custom_metric_below",
            "custom");
    public static final Set<String> ACTION_TYPES = Set.of(
            "noop",
            "unlock_mission",
            "start_mission",
            "complete_mission",
            "complete_objective",
            "unlock_lore",
            "unlock_archive_entry",
            "unlock_terminal_tab",
            "unlock_holomap_layer",
            "add_holomap_marker",
            "change_reputation",
            "trigger_weather",
            "play_sound",
            "show_tutorial_hint",
            "give_item",
            "set_world_state",
            "clear_world_state",
            "set_branch_marker",
            "clear_branch_marker",
            "record_dialogue_choice",
            "spawn_poi",
            "start_dialogue",
            "unlock_index_recipe",
            "add_terminal_alert",
            "set_custom_metric",
            "change_custom_metric",
            "custom");
    public static final Set<String> OBJECTIVE_TYPES = Set.of(
            "collect_item",
            "craft_item",
            "obtain_item",
            "scan_block",
            "scan_entity",
            "scan_item",
            "visit_poi",
            "enter_region",
            "kill_entity",
            "survive_weather",
            "interact_block",
            "build_structure",
            "complete_mission",
            "set_world_state",
            "custom");

    private EchoScriptKnownTypes() {
    }
}
