org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
mod_id=echohazardcore
mod_name=ECHO: HazardCore
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=com.knoxhack.echo.hazardcore
mod_authors=KnoxHack
mod_description=Generic hazards for heat, cold, radiation, oxygen, pressure, corruption, disease, and storm exposure.
