package com.knoxhack.echostationfall.registry;

import com.knoxhack.echo.adaptercore.EchoBackendRegistryBridge;
import com.knoxhack.echo.adaptercore.EchoBackendRegistryEntry;
import com.knoxhack.echostationfall.EchoStationfall;
import com.knoxhack.echostationfall.integration.StationfallOrbitalCompat;
import com.knoxhack.echostationfall.integration.StationfallSuitState;
import com.knoxhack.echostationfall.progression.*;
import com.knoxhack.echostationfall.world.*;
import java.util.*;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.server.level.*;
import net.minecraft.world.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.*;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;

public final class ModItems { public static final Object ITEMS=EchoBackendRegistryBridge.create(BuiltInRegistries.ITEM,EchoStationfall.MODID); private static final List<EchoBackendRegistryEntry<? extends Item>> CREATIVE=new ArrayList<>(); public static final EchoBackendRegistryEntry<Item> STATION_ACCESS_CARD=item("station_access_card",StationAccessCardItem::new,p->p.stacksTo(1).rarity(Rarity.UNCOMMON)); public static final EchoBackendRegistryEntry<Item> PRESSURE_SEAL_KIT=item("pressure_seal_kit",PressureSealKitItem::new,p->p.stacksTo(16)); public static final EchoBackendRegistryEntry<Item> EMERGENCY_OXYGEN_PACK=item("emergency_oxygen_pack",EmergencyOxygenPackItem::new,p->p.stacksTo(8)); public static final EchoBackendRegistryEntry<Item> STATION_BATTERY=simple("station_battery",p->p.rarity(Rarity.UNCOMMON)); public static final EchoBackendRegistryEntry<Item> HULL_CUTTER=simple("hull_cutter",p->p.stacksTo(1).durability(256).rarity(Rarity.UNCOMMON)); public static final EchoBackendRegistryEntry<Item> CREW_LOG_TABLET=simple("crew_log_tablet",p->p.stacksTo(16).rarity(Rarity.UNCOMMON)); public static final EchoBackendRegistryEntry<Item> AI_OVERRIDE_CHIP=item("ai_override_chip",AiOverrideChipItem::new,p->p.stacksTo(1).rarity(Rarity.RARE)); public static final EchoBackendRegistryEntry<Item> SIGNAL_PANIC_DAMPENER=item("signal_panic_dampener",SignalPanicDampenerItem::new,p->p.stacksTo(1).durability(128).rarity(Rarity.RARE)); public static final EchoBackendRegistryEntry<Item> STATIONFALL_BLACKBOX=simple("stationfall_blackbox",p->p.stacksTo(1).rarity(Rarity.EPIC).fireResistant()); public static final EchoBackendRegistryEntry<Item> AI_OVERRIDE_CORE=simple("ai_override_core",p->p.stacksTo(1).rarity(Rarity.EPIC).fireResistant()); public static final EchoBackendRegistryEntry<Item> ORBITAL_MEMORY_FRAGMENT=simple("orbital_memory_fragment",p->p.rarity(Rarity.RARE).fireResistant());
 public static final EchoBackendRegistryEntry<Item> HOLLOW_CREWMAN_SPAWN=spawn("hollow_crewman_spawn",ModEntities.HOLLOW_CREWMAN), EVA_STALKER_SPAWN=spawn("eva_stalker_spawn",ModEntities.EVA_STALKER), MEDICAL_HUSK_SPAWN=spawn("medical_husk_spawn",ModEntities.MEDICAL_HUSK), HYDROPONIC_GROWTH_SPAWN=spawn("hydroponic_growth_spawn",ModEntities.HYDROPONIC_GROWTH), MAINTENANCE_DRONE_SPAWN=spawn("maintenance_drone_spawn",ModEntities.MAINTENANCE_DRONE), SCREAMING_SIGNAL_SPAWN=spawn("screaming_signal_spawn",ModEntities.SCREAMING_SIGNAL), STATION_MIMIC_SPAWN=spawn("station_mimic_spawn",ModEntities.STATION_MIMIC), SUIT_WITHOUT_BODY_SPAWN=spawn("suit_without_body_spawn",ModEntities.SUIT_WITHOUT_BODY), STATION_MOTHER_SPAWN=spawn("station_mother_spawn",ModEntities.STATION_MOTHER);
 static { ModBlocks.ALL_BLOCKS.forEach(b->tracked(blockItem(b.id().getPath(),b))); } private ModItems(){} public static void register(Object b){EchoBackendRegistryBridge.registerEventBus(ITEMS,b);} public static List<EchoBackendRegistryEntry<? extends Item>> creativeItems(){return List.copyOf(CREATIVE);} private static EchoBackendRegistryEntry<Item> simple(String n,UnaryOperator<Item.Properties> p){return item(n,Item::new,p);} private static EchoBackendRegistryEntry<Item> spawn(String n,Supplier<? extends EntityType<? extends Mob>> t){return item(n,pr->new StationSpawnItem(t,pr),p->p.stacksTo(16));} private static EchoBackendRegistryEntry<BlockItem> blockItem(String n,EchoBackendRegistryEntry<? extends Block> block){return EchoBackendRegistryBridge.registerWithId(ITEMS,n,id->new BlockItem(block.get(),new Item.Properties().setId(ResourceKey.create(Registries.ITEM,id)).useBlockDescriptionPrefix()));} private static <T extends Item> EchoBackendRegistryEntry<T> item(String n,Function<Item.Properties,T> f,UnaryOperator<Item.Properties> p){return tracked(EchoBackendRegistryBridge.registerWithId(ITEMS,n,id->f.apply(p.apply(new Item.Properties().setId(ResourceKey.create(Registries.ITEM,id))))));} private static <T extends Item> EchoBackendRegistryEntry<T> tracked(EchoBackendRegistryEntry<T> i){CREATIVE.add(i);return i;} private static void consume(Player p,InteractionHand h){if(!p.hasInfiniteMaterials())p.getItemInHand(h).shrink(1);} 
 public static final class StationAccessCardItem extends Item{public StationAccessCardItem(Properties p){super(p);} public InteractionResult use(Level l,Player p,InteractionHand h){if(l.isClientSide())return InteractionResult.SUCCESS; if(p instanceof ServerPlayer sp){if(StationfallDimensions.isStation(l)&&p.isShiftKeyDown())return StationfallRouteService.returnFromStation(sp)?InteractionResult.SUCCESS_SERVER:InteractionResult.CONSUME; StationfallProgress progress=StationfallProgress.get(p); if(!StationfallOrbitalCompat.orbitalLoaded()&&!progress.canBoard(p)){progress.unlockCoordinates(p);p.sendSystemMessage(Component.literal("ECHO-7 // Standalone Stationfall coordinates recovered from the access card."));} return StationfallRouteService.board(sp,"access_card")?InteractionResult.SUCCESS_SERVER:InteractionResult.CONSUME;} return InteractionResult.CONSUME;}}
 public static final class PressureSealKitItem extends Item{public PressureSealKitItem(Properties p){super(p);} public InteractionResult use(Level l,Player p,InteractionHand h){if(!l.isClientSide()){StationfallSuitState s=StationfallSuitState.get(p);s.applySealantPatch();s.save(p);consume(p,h);com.knoxhack.echostationfall.integration.StationfallMissionHooks.recordPressureStabilized(p,"pressure_seal_kit");p.sendSystemMessage(Component.literal("ECHO-7 // Pressure Seal Kit applied. Hull integrity locally improved."));} return InteractionResult.SUCCESS_SERVER;}}
 public static final class EmergencyOxygenPackItem extends Item{public EmergencyOxygenPackItem(Properties p){super(p);} public InteractionResult use(Level l,Player p,InteractionHand h){if(!l.isClientSide()){StationfallSuitState s=StationfallSuitState.get(p);s.boostOxygen(60);s.save(p);consume(p,h);com.knoxhack.echostationfall.integration.StationfallMissionHooks.recordOxygenStabilized(p,"emergency_oxygen_pack");p.sendSystemMessage(Component.literal("ECHO-7 // Emergency oxygen pack vented into suit reserves."));} return InteractionResult.SUCCESS_SERVER;}}
 public static final class AiOverrideChipItem extends Item{public AiOverrideChipItem(Properties p){super(p);} public InteractionResult use(Level l,Player p,InteractionHand h){if(!l.isClientSide()){StationfallProgress.get(p).markAiOverrideObtained(p);p.sendSystemMessage(Component.literal("ECHO-7 // AI Override Chip synchronized. Station Mother will hear this."));} return InteractionResult.SUCCESS_SERVER;}}
 public static final class SignalPanicDampenerItem extends Item{public SignalPanicDampenerItem(Properties p){super(p);} public InteractionResult use(Level l,Player p,InteractionHand h){if(!l.isClientSide()){SignalPanicState s=SignalPanicState.get(p);s.decay(p,35);p.getItemInHand(h).hurtAndBreak(1,p,h);com.knoxhack.echostationfall.integration.StationfallMissionHooks.recordPanicDampened(p,"signal_panic_dampener");p.sendSystemMessage(Component.literal("ECHO-7 // Dampener pulse fired. Signal Panic reduced to "+s.value()+"%."));} return InteractionResult.SUCCESS_SERVER;}}
 public static final class StationSpawnItem extends Item{private final Supplier<? extends EntityType<? extends Mob>> type; public StationSpawnItem(Supplier<? extends EntityType<? extends Mob>> t,Properties p){super(p);type=t;} public InteractionResult use(Level l,Player p,InteractionHand h){if(l.isClientSide())return InteractionResult.SUCCESS; if(l instanceof ServerLevel sl){BlockPos pos=p.blockPosition().offset(0,1,2);Entity e=type.get().create(sl,EntitySpawnReason.SPAWN_ITEM_USE); if(e!=null){e.setPos(pos.getX()+.5,pos.getY(),pos.getZ()+.5);sl.addFreshEntity(e);consume(p,h);}} return InteractionResult.SUCCESS_SERVER;}}
}
