package com.knoxhack.echonexusprotocol.client;

import com.knoxhack.echocore.client.ui.EchoCyberGlassUi;
import com.knoxhack.echonexusprotocol.block.entity.NexusMachineBlockEntity.MachineStatus;
import com.knoxhack.echonexusprotocol.menu.NexusMachineMenu;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.network.chat.Component;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.inventory.Slot;

import java.util.List;

public class NexusMachineScreen extends AbstractContainerScreen<NexusMachineMenu> {
   public NexusMachineScreen(NexusMachineMenu menu, Inventory inventory, Component title) { super(menu, inventory, title, NexusMachineMenu.GUI_WIDTH, NexusMachineMenu.GUI_HEIGHT); this.titleLabelX = 16; this.titleLabelY = 14; this.inventoryLabelX = NexusMachineMenu.PLAYER_INV_X; this.inventoryLabelY = NexusMachineMenu.PLAYER_INV_Y - 13; }
   public void extractContents(GuiGraphicsExtractor graphics, int mouseX, int mouseY, float partialTick) { int x = this.leftPos, y = this.topPos; graphics.fill(x, y, x + this.imageWidth, y + this.imageHeight, 0xF006101A); graphics.fill(x, y, x + this.imageWidth, y + 2, 0xFF66E8FF); graphics.fill(x, y + this.imageHeight - 2, x + this.imageWidth, y + this.imageHeight, 0xFF9F5BFF); graphics.fill(x, y, x + 2, y + this.imageHeight, 0xFF66E8FF); graphics.fill(x + this.imageWidth - 2, y, x + this.imageWidth, y + this.imageHeight, 0xFF9F5BFF); graphics.fill(x + 2, y + 2, x + this.imageWidth - 2, y + 42, 0xDD101820); graphics.fill(x + 18, y + 54, x + this.imageWidth - 18, y + 206, 0xAA090B16); for (int i = 0; i < this.menu.slots.size(); i++) { Slot slot = this.menu.slots.get(i); drawSlot(graphics, x + slot.x, y + slot.y, i == 1 ? 0xFF151029 : 0xFF0B1620); } graphics.fill(x + 118, y + 96, x + 230, y + 104, 0xFF293443); graphics.fill(x + 118, y + 96, x + 118 + progressPixels(112), y + 104, 0xFF6FE6FF); graphics.fill(x + 118, y + 118, x + 230, y + 126, 0xFF293443); graphics.fill(x + 118, y + 118, x + 118 + chargePixels(112), y + 126, 0xFF70F0D8); graphics.fill(x + 118, y + 140, x + 230, y + 148, 0xFF293443); graphics.fill(x + 118, y + 140, x + 118 + contaminationPixels(112), y + 148, 0xFFB85CFF); super.extractContents(graphics, mouseX, mouseY, partialTick); drawStatus(graphics, x, y); drawHoverHelp(graphics, x, y, mouseX, mouseY); }
   protected void extractLabels(GuiGraphicsExtractor graphics, int mouseX, int mouseY) { graphics.text(this.font, fit(this.title.getString(), 214), this.titleLabelX, this.titleLabelY, 0x66E8FF, true); graphics.text(this.font, this.playerInventoryTitle, this.inventoryLabelX, this.inventoryLabelY, 0xD8F6FF, false); }
   private void drawStatus(GuiGraphicsExtractor graphics, int x, int y) { MachineStatus statusId = MachineStatus.byId(this.menu.statusId()); String status = statusText(statusId); graphics.text(this.font, Component.literal(fit(this.menu.machineKind().displayName() + " // " + status, 284)), x + 28, y + 154, statusColor(statusId), false); graphics.text(this.font, Component.literal("Progress " + this.menu.progress() + "/" + Math.max(1, this.menu.maxProgress())), x + 118, y + 108, 0xAEEBFF, false); graphics.text(this.font, Component.literal("Charge " + this.menu.charge() + "/" + Math.max(1, this.menu.maxCharge())), x + 118, y + 130, this.menu.charge() <= 0 ? 0xFFD166 : 0x88F4FF, false); graphics.text(this.font, Component.literal("Contamination " + this.menu.contamination() + "%"), x + 118, y + 152, this.menu.contamination() >= 75 ? 0xFFFF6B9A : 0xD7B0FF, false); graphics.text(this.font, Component.literal(fit(machineHint(statusId), 284)), x + 28, y + 172, 0x8CB8C2, false); graphics.text(this.font, Component.literal("IN"), x + NexusMachineMenu.INPUT_X + 3, y + 76, 0x8CB8C2, false); graphics.text(this.font, Component.literal("OUT"), x + NexusMachineMenu.OUTPUT_X, y + 76, 0x8CB8C2, false); }
   private String statusText(MachineStatus status) { return switch (status) { case BAD_INPUT -> "Input rejected: check JEI or Nexus route"; case OUTPUT_BLOCKED -> "Output blocked: clear or stack result"; case CHARGING -> "Missing Nexus Charge: relay from tank/recycler"; case LEAKING -> "Containment leak: filter or repair now"; case PURIFYING -> "Filtering contamination and pressure"; case STABILIZING -> "Field recovery active"; case REACTING -> "Forbidden reactor active: watch Field Map"; case COMPLETE -> "Cycle complete: route progress indexed"; default -> status.label(); }; }
   private int statusColor(MachineStatus status) { return switch (status) { case BAD_INPUT, OUTPUT_BLOCKED, LEAKING -> 0xFFFF6B9A; case CHARGING -> 0xFFFFD166; case COMPLETE, PURIFYING, STABILIZING -> 0xFF8CFFB8; default -> 0xD8F6FF; }; }
   private String machineHint(MachineStatus status) { return switch (status) { case BAD_INPUT -> "Try JEI or Terminal recipes; invalid inputs will not be consumed."; case OUTPUT_BLOCKED -> "Move the output before continuing the route."; case CHARGING -> "Relay charge from a tank, recycler, or Collapse seal before long crafts."; case LEAKING -> "Run a Corruption Filter, repair seal, or move dirty machines out of this chunk."; case REACTING -> "Check Nexus Field Map and keep recovery tools ready."; default -> "Sneak-use the block for a compact ECHO-7 status readout."; }; }
   private void drawHoverHelp(GuiGraphicsExtractor graphics, int x, int y, int mouseX, int mouseY) { List<String> lines = null; if (inside(mouseX, mouseY, x + NexusMachineMenu.INPUT_X - 1, y + NexusMachineMenu.MACHINE_SLOT_Y - 1, 18, 18)) lines = List.of("Valid inputs depend on this machine.", "Bad inputs create no progress and may warn."); else if (inside(mouseX, mouseY, x + NexusMachineMenu.OUTPUT_X - 1, y + NexusMachineMenu.MACHINE_SLOT_Y - 1, 18, 18)) lines = List.of("Output slot must be empty or stackable.", "Clear it if progress stalls."); else if (inside(mouseX, mouseY, x + 118, y + 96, 112, 8)) lines = List.of("Processing progress", this.menu.progress() + " / " + Math.max(1, this.menu.maxProgress()), "Fix: add valid input, charge, or clear output."); else if (inside(mouseX, mouseY, x + 118, y + 118, 112, 8)) lines = List.of("Nexus Charge buffer", this.menu.charge() + " / " + Math.max(1, this.menu.maxCharge()), this.menu.charge() <= 0 ? "Missing charge: route from a tank or relay." : "Keep buffers stable for faster cycles."); else if (inside(mouseX, mouseY, x + 118, y + 140, 112, 8)) lines = List.of("Contamination risk", this.menu.contamination() + "%", this.menu.contamination() >= 75 ? "High risk: filter, repair, or move machines." : "Dirty inputs and reactors raise this value."); if (lines != null) drawTooltipPanel(graphics, mouseX, mouseY, lines); }
   private void drawTooltipPanel(GuiGraphicsExtractor graphics, int mouseX, int mouseY, List<String> lines) { EchoCyberGlassUi.tooltipPanel(graphics, this.font, mouseX, mouseY, this.leftPos, this.topPos, this.imageWidth, this.imageHeight, lines); }
   private boolean inside(int mouseX, int mouseY, int x, int y, int width, int height) { return mouseX >= x && mouseX < x + width && mouseY >= y && mouseY < y + height; }
   private void drawSlot(GuiGraphicsExtractor graphics, int x, int y, int fill) { EchoCyberGlassUi.slot(graphics, x, y, fill); } private int progressPixels(int width) { int max = this.menu.maxProgress(); return max <= 0 ? 0 : Math.min(width, this.menu.progress() * width / max); } private int chargePixels(int width) { int max = Math.max(1, this.menu.maxCharge()); return Math.min(width, this.menu.charge() * width / max); } private int contaminationPixels(int width) { return Math.min(width, this.menu.contamination() * width / 100); } private String fit(String text, int maxWidth) { if (this.font.width(text) <= maxWidth) return text; String suffix = "..."; int suffixW = this.font.width(suffix); return this.font.plainSubstrByWidth(text, Math.max(0, maxWidth - suffixW)) + suffix; }
}
