package com.knoxhack.echo.platformcore;

public enum EchoModuleRole {
    RUNTIME_CORE("runtime_core"),
    NETWORK_CORE("network_core"),
    DATA_CORE("data_core"),
    PLATFORM_CORE("platform_core"),
    ADAPTER_CORE("adapter_core"),
    VALIDATION_CORE("validation_core"),
    SCHEMA_CORE("schema_core"),
    METADATA_CORE("metadata_core"),
    MODULE_GRAPH("module_graph"),
    HEALTH_CORE("health_core"),
    RECOVERY_CORE("recovery_core"),
    AGENT_CORE("agent_core"),
    BRIDGE_CORE("bridge_core"),
    REPORT_CORE("report_core"),
    CONTENT_CORE("content_core"),
    RECIPE_CORE("recipe_core"),
    PROGRESSION_CORE("progression_core"),
    OBJECTIVE_CORE("objective_core"),
    SOCIAL_CORE("social_core"),
    FACTION_CORE("faction_core"),
    DIALOGUE_CORE("dialogue_core"),
    NPC_CORE("npc_core"),
    ECONOMY_CORE("economy_core"),
    LOOT_CORE("loot_core"),
    STRUCTURE_CORE("structure_core"),
    STATUS_CORE("status_core"),
    COMBAT_CORE("combat_core"),
    CREATURE_CORE("creature_core"),
    SPAWN_CORE("spawn_core"),
    EVENT_CORE("event_core"),
    ENCOUNTER_CORE("encounter_core"),
    DIFFICULTY_CORE("difficulty_core"),
    QUEST_DIRECTOR("quest_director"),
    HUD_CORE("hud_core"),
    NOTIFICATION_CORE("notification_core"),
    GUIDE_CORE("guide_core"),
    CODEX_CORE("codex_core"),
    LORE_CORE("lore_core"),
    ASSET_CORE("asset_core"),
    POWER_CORE("power_core"),
    MACHINE_CORE("machine_core"),
    LOGISTICS_CORE("logistics_core"),
    VEHICLE_CORE("vehicle_core"),
    BIOME_CORE("biome_core"),
    ATMOSPHERE_CORE("atmosphere_core"),
    CINEMATIC_CORE("cinematic_core"),
    CAMERA_CORE("camera_core"),
    INPUT_CORE("input_core"),
    PACK_CORE("pack_core"),
    AI_TOOL("ai_tool"),
    BRIDGE_TOOL("bridge_tool"),
    DEV_TOOL("dev_tool"),
    GAME_ROOT("game_root"),
    CONTENT_EXPANSION("content_expansion"),
    MISSION_BACKEND("mission_backend"),
    WORLD_BACKEND("world_backend"),
    REGION_BACKEND("region_backend"),
    FACTION_BACKEND("faction_backend"),
    NPC_BACKEND("npc_backend"),
    DIALOGUE_BACKEND("dialogue_backend"),
    RECIPE_BACKEND("recipe_backend"),
    PROGRESSION_BACKEND("progression_backend"),
    OBJECTIVE_BACKEND("objective_backend"),
    STATUS_BACKEND("status_backend"),
    EVENT_BACKEND("event_backend"),
    ENCOUNTER_BACKEND("encounter_backend"),
    SPAWN_BACKEND("spawn_backend"),
    DIFFICULTY_BACKEND("difficulty_backend"),
    TERMINAL_SURFACE("terminal_surface"),
    INDEX_SURFACE("index_surface"),
    SCANNER_SURFACE("scanner_surface"),
    MAP_SURFACE("map_surface"),
    HUD_SURFACE("hud_surface"),
    SCREEN_FRAMEWORK("screen_framework"),
    THEME_PACK("theme_pack"),
    RENDER_BACKEND("render_backend"),
    AUDIO_BACKEND("audio_backend"),
    WEATHER_BACKEND("weather_backend"),
    TUTORIAL_BACKEND("tutorial_backend"),
    GUIDE_BACKEND("guide_backend"),
    ECONOMY_BACKEND("economy_backend"),
    LOOT_BACKEND("loot_backend"),
    STRUCTURE_BACKEND("structure_backend"),
    POWER_BACKEND("power_backend"),
    MACHINE_BACKEND("machine_backend"),
    LOGISTICS_BACKEND("logistics_backend"),
    VEHICLE_BACKEND("vehicle_backend"),
    COMBAT_BACKEND("combat_backend"),
    CREATURE_BACKEND("creature_backend"),
    BIOME_BACKEND("biome_backend"),
    ATMOSPHERE_BACKEND("atmosphere_backend"),
    CINEMATIC_BACKEND("cinematic_backend"),
    CAMERA_BACKEND("camera_backend"),
    INPUT_BACKEND("input_backend"),
    ASSET_TOOL("asset_tool");

    private final String serializedName;

    EchoModuleRole(String serializedName) {
        this.serializedName = serializedName;
    }

    public String serializedName() {
        return serializedName;
    }
}
